### ISSUE TITLE
Hi, some question hope to answer, thanks

### ISSUE THREAD

**Issue by zhuwengit** [huankiki/OMLSA-IMCRA-Note#1]
1. New version and new version omlsa3 correspond to that paper?
2. Which formula corresponds to GH0 in the code？

**Comment by huankiki** [comment]
1, to my understanding, the comment at matlab script doesn't mean a new version, just a combination of the TWO algorithm papers, as list in Cohen's website ( website link already listed at README.md);
2, please carefully read Cohen's papers and my note at /doc/OMLSA_IMCRA_Note_share.pdf, which already list formula equation number. GH0 mean Gmin from dB value to normal gain value.

**Comment by zhuwengit** [comment]
Thank you very much for your reply, the reference paper and your notes have been read. There are still some specific questions in the MATLAB code section：
1.        if tone_flag   % new version
            lambda_d_global=lambda_d;   % new version
            lambda_d_global(4:M21-3)=min([lambda_d_global(4:M21-3),lambda_d_global(1:M21-6),lambda_d_global(7:M21)],[],2);   % new version
            Sy=0.8*Sy+0.2*Ya2;    % new version
            %             GH0=G_f*(lambda_d_global./Sy).^0.5;   % new version       % new version omlsa3
            GH0=G_f*(lambda_d_global./(Sy+1e-10)).^0.5;   % new version omlsa3
        else   % new version
2. In the above code, the solutions of parameters lambda_d_global, Sy and GH0 are not found in the corresponding reference. Could you please explain? 
Thanks again, best wishes！！！

**Comment by huankiki** [comment]
sorry, I didn't find the corresponding reference either.

**Comment by zhuwengit** [comment]
ok, thanks again for your reply, good luck！
