### ISSUE TITLE
Here are some questions ，thank you。  

### ISSUE THREAD

**Issue by awer415** [huankiki/OMLSA-IMCRA-Note#2]
1.About <Small speech signal with most energy in higher frequency, has some distortion>，Is there an optimization algorithm to improve the distortion problem?
2.As for the source of the code, is the code in Git open-source by Cohen, or is it reproduced by you?

**Comment by huankiki** [comment]
1, sorry, still in my to-do list, need more test and study;
2, Cohen's website has the code, my version did some modification as descripted at README. please check Cohen's website by yourself.
